# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Example add-on
version: "0.0.1"
slug: example
description: Example add-on
startup: "application"
url: "https://github.com/home-assistant/addons-example/tree/main/example"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
ports:
  8080/tcp: 8080
ingress: true
ingress_port: 8080
options:
  zim_urls:
    - "https://dumps.wikimedia.org/other/kiwix/zim/wikipedia/wikipedia_en_100_2024-02.zim"
schema:
  zim_urls:
    - url
